import { ThemeProvider } from "@/components/theme-provider";
import Providers from "@/lib/Providers";
import React, { ReactNode, Suspense } from "react";
import { Toaster } from "sonner";
import { Toaster as HotToaster } from "react-hot-toast";
import Loading from "./(auth)/loading";
import { Metadata } from "next";
import { Josefin_Sans, Poppins } from "next/font/google";
import Custom from "./_components/Custom";

const poppins = Poppins({
  variable: "--font-Poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const josefin = Josefin_Sans({
  variable: "--font-Josefin",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "ELearning",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${josefin.variable} ${poppins.variable} overflow-x-hidden`}
      >
        <Suspense fallback={<Loading />}>
          <Providers>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem={false}
              disableTransitionOnChange
            >
              <Custom>{children}</Custom>
              <Toaster position="top-center" />
              <HotToaster reverseOrder={false} />
            </ThemeProvider>
          </Providers>
        </Suspense>
      </body>
    </html>
  );
};

export default RootLayout;
