import type { Metadata } from "next";
import { Josefin_Sans, Poppins } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/shared/Navbar";

import Footer from "@/components/home/Footer";
import { Suspense } from "react";
import Loading from "./loading";
import ScrollToTop from "@/components/ScrollToTop";

const poppins = Poppins({
  variable: "--font-Poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Add appropriate weights as needed
});

const josefin = Josefin_Sans({
  variable: "--font-Josefin",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Add appropriate weights as needed
});

export const metadata: Metadata = {
  title: "ELearning",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.variable} ${josefin.variable} overflow-x-hidden bg-gray-50 dark:bg-[#0C111B]    dark:bg-gradient-to-r from-[#0C111B] to-[#131c36] `}
      >
        <div>
          <Suspense fallback={<Loading />}>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem={false}
              disableTransitionOnChange
            >
              <Navbar />
              {children}
              <Footer />
              <ScrollToTop />
            </ThemeProvider>
          </Suspense>
        </div>
      </body>
    </html>
  );
}

//bg-gradient-to-b from-white to-gray-50 dark:from-[#0C111B] dark:to-[#131c36]
// /bg-gray-50 dark:bg-[#0C111B]

//overflow-x-hidden !bg-white bg-no-repeat dark:bg-gradient-to-b dark:from-gray-900 dark:to-black duration-300
