import type { Metadata } from "next";
import { Mona_Sans } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Suspense } from "react";
import Loading from "./loading";
import Providers from "@/lib/Providers";
import { Toaster } from "@/components/ui/sonner";
import { Toaster as HotToaster } from "react-hot-toast";


const monaSans = Mona_Sans({
  variable: "--font-mona-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LMS",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className={`${monaSans.variable} `}>
        <div>
          <Suspense fallback={<Loading />}>
            <Providers>
                <ThemeProvider
                  attribute="class"
                  defaultTheme="dark"
                  enableSystem={false}
                  disableTransitionOnChange
                >
                  {children}
                  <Toaster position="top-center" />
                  <HotToaster reverseOrder={false} />
                </ThemeProvider>
              
            </Providers>
          </Suspense>
        </div>
      </body>
    </html>
  );
}
